name: Cypress E2E tests

on:
  pull_request:
    types: [ opened ]
    branches: [ master ]

jobs:

  check-commit-message:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: PR's title convention
    steps:
      - name: Check PR's title convention
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '(feat|fix|docs|chore|test|style|refactor|release|bump)\[\#([0-9]+)\]:\s.+$'
          flags: 'gm'
          error: 'Your first line has to contain a commit type like "feat[#number]:".'

  install:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Install prerequisite stuffs
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: check-commit-message
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      # report machine parameters
      - run: yarn cypress version

  tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: Running the tests
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            build
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-

      - name: "UI Tests"
        uses: cypress-io/github-action@v2
        id: cypress-tests
        with:
          ## specify the viewport for the mobile potential
          # config: "viewportWidth=375,viewportHeight=667" 
          start: yarn run serve
          wait-on: "http://localhost:8080"
          wait-on-timeout: 360000
          browser: chrome
          spec: tests/e2e/specs/*

      - name: Sending failure notification
        if: failure()
        uses: actions/github-script@v4
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          TO_EMAILS: ${{ secrets.TO_EMAILS }}
          GITHUB_JOB: ${{ github.job }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_REPO: ${{ github.repository }}
          JOB_STATUS: ${{ job.status }}
        with:
          script: |
            const nodemailer = require('nodemailer')
            const { google } = require('googleapis')
            const OAuth2 = google.auth.OAuth2

            const { CLIENT_ID, CLIENT_SECRET, REFRESH_TOKEN, FROM_EMAIL, TO_EMAILS } = process.env
            const { GITHUB_JOB, GITHUB_WORKFLOW, GITHUB_REPO, JOB_STATUS } = process.env

            const oauth2Client = new OAuth2(
              CLIENT_ID,
              CLIENT_SECRET,
              'https://developers.google.com/oauthplayground'
            )

            oauth2Client.setCredentials({ refresh_token: REFRESH_TOKEN })

            const ACCESS_TOKEN = oauth2Client.getAccessToken()

            const smtpTransport = nodemailer.createTransport({
              service: 'gmail',
              auth: {
                type: 'OAuth2',
                user: FROM_EMAIL, 
                clientId: CLIENT_ID,
                clientSecret: CLIENT_SECRET,
                refreshToken: REFRESH_TOKEN,
                accessToken: ACCESS_TOKEN
              },
              tls: {
                rejectUnauthorized: false
              }
            })

            const mailOptions = {
              from: FROM_EMAIL,
              to: TO_EMAILS,
              subject: '[Git Actions] PR failed on some checks',
              html: `
                <p>Helle there!</p>
                <p>The <strong>${ GITHUB_JOB }</strong> job in workflow <strong>${ GITHUB_WORKFLOW }</strong> of <strong>${ GITHUB_REPO }</strong> has <strong>${ JOB_STATUS }</strong></p>
              `
            }

            smtpTransport.sendMail(mailOptions, function(error, info){})
